name: Test CI

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Test CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Hyperlane dependencies setup
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'lib/hyperlane-monorepo'

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          MOONBASE_RPC_URL: ${{ secrets.MOONBASE_RPC_URL }}
          GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
